### ISSUE TITLE
Formatting Codes are not being correctly handled

### ISSUE THREAD

**Issue by foursixnine** [benignbala/pod-asciidoctor#3]
Currently i have the following pod code

```perl
=head2 autoinst_url

  autoinst_url([$path, $query]);

returns the base URL to contact the local C<os-autoinst> service

Optional C<$path> argument is appended after base url. 

Optional HASHREF C<$query> is converted to URL query and appended
after path.

Returns constructor URL. Can be used inline:

  script_run("curl " . autoinst_url . "/data");

=cut
```

That when used in conjunction with this parser, generates the following output, which is not correctly rendered:
![screenshot from 2016-12-27 16-03-04](https://cloud.githubusercontent.com/assets/229240/21502150/1163fe98-cc4e-11e6-806b-95ef75f3d972.png)

Which is obviously not parsing C<foo> and along the rest of the .pm module, other formattings... 

The expected output is: 
![screenshot from 2016-12-27 16-03-27](https://cloud.githubusercontent.com/assets/229240/21502151/116464a0-cc4e-11e6-9e49-e5a98606b80d.png)

Which is solved by using: `$paragraph = $self->interpolate($paragraph);` and adding the correct interior_sequence method.

**Comment by benignbala** [comment]
Fixed by PR #4
